### ISSUE TITLE
Top padding should be removed on the first block of a cell

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor-docs-ui#10]
As you can see above, the listing blocks are misaligned:

![current](https://user-images.githubusercontent.com/333276/99189273-af84ed00-2760-11eb-8762-2f3d1d25518e.png)

And here's the result when the top padding is removed:

![remove-top-padding](https://user-images.githubusercontent.com/333276/99189270-aeec5680-2760-11eb-9809-8f044e0cd91e.png)

Should we fix this issue [upstream](https://gitlab.com/antora/antora-ui-default/) as well?

**Comment by mojavelinux** [comment]
I didn't see this issue, but I had the same observation and fixed it in 2f294fbe4da6fccdc3f11d312a81f1ad3e9576d5 and 21784290a0f34c63709bfe6161459cd9565103e8. I also fixed it upstream.
