### ISSUE TITLE
Unable to select the last character of a listing block...

### ISSUE THREAD

**Issue by ggrossetie** [asciidoctor/asciidoctor-docs-ui#130]
...without copying the language and "Copy to clipboard" text.

![select-text](https://github.com/asciidoctor/asciidoctor-docs-ui/assets/333276/46ae5b88-e153-43c2-937c-406d562ddc09)

I think we should use `user-select: none` on `source-toolbox`.

With this setting, it's better but still a bit odd:

![select-text-ok](https://github.com/asciidoctor/asciidoctor-docs-ui/assets/333276/200c560e-1925-4962-9002-7bcb283eaa30)

If I remove the `source-toolbox` completely then it's working as expected:

![select-good](https://github.com/asciidoctor/asciidoctor-docs-ui/assets/333276/b53ab3a8-7c11-4b11-ae24-20ae1c24c525)

**Comment by mojavelinux** [comment]
This appears to be specific to Chrome/Chromium, and thus strikes me as a browser bug. I don't observe this behavior with Firefox.

That said, I'm not opposed to the workaround you suggested. If you comfortable with it, or have an idea of how else to workaround this bug, feel free to apply a fix for it.

**Comment by ggrossetie** [comment]
Indeed, it's better on Firefox but it's still possible to select the text:

https://github.com/asciidoctor/asciidoctor-docs-ui/assets/333276/a5a4968c-27ba-4e14-b74c-7e35ae2eb853

I will try to find something that works on both Firefox and Chrome.

**Comment by mojavelinux** [comment]
I look forward to it!

**Comment by mojavelinux** [comment]
The issue with `user-select: none` is only a visible one. It doesn't actually copy any additional characters. I'm not sure why Chrome does it, but it seems to me like some sort of visual selection bug.
