### ISSUE TITLE
Add project (aka component) filter to search

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-docs-ui#37]
Add a filter to the search so its possible to limit search results to a given project (i.e., component).

Each record is marked with a facet (i.e., field) named `component` that corresponds to the name of the component for that record. This facet can be passed to the search query (as a child of `algoliaOptions`). See https://www.algolia.com/doc/api-reference/api-parameters/facetFilters/?client=javascript

```js
facetFilters: ['component:asciidoctor.js']
```

A simple solution would be to provide a select field next to the input to control the component facet value. Here are possible values for that select field:

* All projects (i.e., no filter), Asciidoctor, Asciidoctor.js, etc
* All projects, In this Project
* All projects, In this project, Asciidoctor, Asciidoctor.js, etc

The first alternative seems like the simplest approach.

**Comment by mojavelinux** [comment]
Another idea is to add options in the autocomplete for more narrow filtering. But since the search box already uses autocomplete for the results, this doesn't seem like a good fit. So the select field may be the best way to go. Perhaps use CSS to try to make it feel like part of the input.

**Comment by Mogztter** [comment]
@mojavelinux I can't find how to dynamically update the facet filters? Apparently, the [`DocSearch` class](https://github.com/algolia/docsearch/blob/master/src/lib/DocSearch.js) does not have a function to configure/update the `algoliaOptions`... :thinking:

**Comment by mojavelinux** [comment]
resolved by #39.
