### ISSUE TITLE
Mantain 'In this project' search option checked when used

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctor-docs-ui#96]
Not sure what's best in term of usability, but at least to me this makes sense based on my expectations.

* I am usually focused on a project, be it Asciidoctorj or Asciidoctor. So I check the search option to limit seach results.
* When I do another subsequent search, the left menu already is limited to a project, so subconsciously I expect the results to mantain the option and be limited to the current project. The oposite is confusing an prone to errors. For instance if I search for "Windows" installation and I am in Asciidoctorj it will show first the results for Asciidoctor, and is easy to overlook the title and select that, then you realize the mistake and have to search again.

**Comment by Mogztter** [comment]
We could use https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage but:

> Opening a page in a new tab or window creates a new session with the value of the top-level browsing context, which differs from how session cookies work.

I think that opening a page in a new tab or window is a common practice when using search, so maybe we should use https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage instead?

Also, I think we should save on which components the "In this project" checkbox has been checked.
For instance, when the checkbox "In this project" has been checked on the Asciidoctor and AsciidoctorJ components, the `localStorage` should contain:


```js
localStorage.setItem('docsearch-facet-filters', 'component:asciidoctor,component:asciidoctorj');
```

We can then use this value to preserve "In this project" search option.
In this specific case, the "In this project" search option will be checked on the Asciidoctor and AsciidoctorJ components and unchecked on the other components.

Thoughts?

**Comment by mojavelinux** [comment]
> I think we should save on which components the "In this project" checkbox has been checked.

I'm not yet convinced about this part. I think that would actually make it more confusing. Now a user has to remember which project they were in when they ticked the box, and if they are moving around different projects while navigating search results, it might strike them as odd that sometimes the state is remembered and other times it isn't. I think we should look at it as a global option. Either the box is checked or it is not checked, and that is remembered.

It also makes the script *a lot* simpler.

> I think that opening a page in a new tab or window is a common practice when using search

I agree that localStorage makes more sense if we want to accommodate this practice. And it certainly doesn't hurt to remember across browser sessions (meaning restarting the browser).

How about we start with the global option and then see if someone comes forward to make the case that it should be more fine-grained than that.

**Comment by mojavelinux** [comment]
I think the "restore previous search" functionality proposed in #104 will satisfy the remaining need.
